config/routes.rb
Rails.application.routes.draw do
  resources :contents
  devise_for :users
  root 'pages#home'
  get 'about' => 'pages#about'

end

app/models/content.rb
class Content < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :contents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
     devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end


end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_user, only:[:edit, :update, :destroy]

  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = current_user.contents.build
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = current_user.contents.build(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:titolo, :descrizione, :price)
    end

     def  check_user
     if current_user != @content_user
       redirect_to root_url, alert:"Scusa ma non hai accesso a questa pagina"
     end
     end
   end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contents/_form.html.erb
<%= form_for(@content) do |f| %>
  <% if @content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% @content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :titolo %><br>
    <%= f.text_field :titolo, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :descrizione %><br>
    <%= f.text_area :descrizione, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, :class => 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit "Send", :class => "btn btn-lg btn-primary btn-block" %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Editing Content</h1>

<%= render 'form' %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="center">Vendi un contenuto digitale</h1>

<table class="table">
  <thead>
    <tr>
      <th>Titolo</th>
      <th>Descrizione</th>
        <th>Utente</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contents.each do |content| %>
      <tr>
        <td><%= content.titolo %></td>
        <td><%= content.descrizione %></td>
        <td><%= content.user.name %></td>
        <td><%= content.price %></td>
        <td><%= link_to 'Show', content %></td>
        <% if content.user == current_user %>
          <td><%= link_to 'Edit', edit_content_path(content) %></td>
          <td><%= link_to 'Destroy', content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Content', new_content_path %>

app/views/contents/new.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3 text-center">
<h1 <h1 class="center">New Content</h1>



<%= render 'form' %>

<%= link_to 'Back', contents_path %>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titolo:</strong>
  <%= @content.titolo %>
</p>

<p>
  <strong>Descrizione:</strong>
  <%= @content.descrizione %>
</p>

<p>
  <strong>Price:</strong>
  <%= @content.price %>
</p>
  <% if @content.user == current_user %>
    <%= link_to 'Edit', edit_content_path(@content) %> |
  <% end %>
<%= link_to 'Back', contents_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaOne</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--     Fonts     -->
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Grand+Hotel' rel='stylesheet' type='text/css'>
</head>
<body>
<%= render 'shared/navbar' %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<div class="container">
<div class="row">
<%= yield %>
</div>
</div>
<%= render 'shared/footer' %></body>
</html>

app/views/pages/about.html.erb
<h1>Chi Siamo</h1>
<p>Molente a Web App</p>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
  Made with <i class="fa fa-heart heart"></i> by <a href="http://www.codicenuragico.com">Codice Nuragico</a>
    </div>
</footer>

app/views/shared/_navbar.html.erb
<!-- Static navbar -->
   <nav class="navbar navbar-default navbar-static-top">
     <div class="container">
       <div class="navbar-header">
         <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
           <span class="sr-only">Toggle navigation</span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
         </button>
         <a class="navbar-brand" href="/">AlphaOne</a>
       </div>
       <div id="navbar" class="navbar-collapse collapse">
         <ul class="nav navbar-nav navbar-right">
           <li><%= link_to "Home", root_path %></li>
           <li><%= link_to "About", about_path %></li>
          <% if user_signed_in? %>
           <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
           <% else %>
           <li><%= link_to "Sign Up", new_user_registration_path, :class => 'btn btn-default btn-sm' %></li>
           <li><%= link_to "Login", new_user_session_path %></li>
           <% end %>
          </ul>
       </div><!--/.nav-collapse -->
     </div>
   </nav>